on:
  push:
    branches:
    - branch1
  pull_request:
    types:
      - opened
jobs:
  run_if:
    if:  startsWith(github.head_ref, 'branch')
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR raised from a branch"
